### ISSUE TITLE
Decoding the signal from the native remote control

### ISSUE THREAD

**Issue by CYSShop** [d1mdev/esphome-whirlpool-ac#4]
Good afternoon. I have set up everything according to your instructions and everything seems to work, but periodically controlling the native remote control commands are not decoded and the air conditioner does not change the state in HA. And accordingly physically, for example, the air conditioner is on, but in HA it is off.  Why does this happen? Have you encountered something like this?

**Comment by d1mdev** [comment]
Hello,
firstly i recommend flash esp fresh version of component with tag 202404.04. It works very well. i personally use it in my AC.

Regarding your question, answer is yes. Sometimes it happens. That's why i provide ir transmitter switch.

> Why does this happen?

I have no deep knowledge in optical hardware and i don't know what type of equipment you use.
Try to slightly change the position of the receiver, it can help better receiption.
Try to catch issue. Open log console in esphome builder and send some commands to AC using native remote control. You have to see records starting with: Received: AA BB CC DD and so on. If you send commands and don't see such records, most likely the problem is a poor-quality signal reception. If you see records, but HA state don't change, it can be problem of decoding the recived  packet and you will see the corresponding error.

**Comment by anpl5555** [comment]
Добрый день. Пишу вам с другого аккаунта. Я посмотрел ваши репозитории и заметил, что вы тоже говорите на русском. Если для вас это не проблема, то предлагаю перейти на него) Мое оборудование это оригинальный пульт Яндекс YNDX-0006 и кондиционер Hisense AS-09HR4RYDDJ00. К сожалению, он не Wi-Fi-Ready и приходится мучаться с пультами. Главная проблема в моем случае заключается в том, что используя родной пульт сигнал не всегда декодируется и в логах вместо четырех или пяти строк (вида MODE: COOL, TEMP: 16 и тд) приходит просто сырой raw. То есть умный пульт видит сигнал, но не перекодирует его в правильный вид. Постепенно увеличивая температуру с 16 до 30 градусов происходит 2-3 пропуска. И если режимы и температура это не так важно, то состояние включен или выключен это критично. То есть физически кондиционер отключили родным пультом, но сигнал не был перекодирован умным пультом и в хоум ассистент он остался включен. Отсюда путаница в состояниях и если выключить его с помощью ХА, то произойдет переключение-в ХА выключено, а физически он включится. Вчера пришла в голову идея включить кондиционер через умную розетку и придумать автоматизацию завязанную на потребление. Потребление более 100 ватт, тогда состояние обновляется на включено. Но ХА не дает обновлять состояние без действия. (( Как говорил ранее, посмотрел ваши репозитории и увидел, что у вас там есть еще пару способов управления кондиционером. Интересней всего тема управления через экранный модуль, который acu2d, но там все этим управляет есп-шка с переходником которого не заказать и не купить. И еще способ через UART но эту тему пока не изучал. Можете подсказать куда копать? В сторону доработки пульта или есть какой-то более элегантный способ? Буду благодарен за ответ.

**Comment by d1mdev** [comment]
Добрый день!
Упражняться в практике иностранного языка имеет смысл с его носителем :)
Судя по модели пульта Яндекс это Туя с перебитым шильдиком со всеми вытекающими. Что там "под капотом" понятия не имею и, честно говоря, не интересуюсь. В инструкции упоминается о возможности обучения Я-пульта командам от родного, как вариант стоит попробовать. Вероятно при настройке вы подобрали не очень удачный аналог и не все команды корректно декодируются.
Для отслеживания состояния вкл/выкл часто применяют датчик открытия окна/двери. Его лепят на шторку кондиционера. Я так отслеживаю. В HA настроил template сенсор, который следит за состоянием кондиционера и состоянием датчика. Если эти состояния не соответствуют - срабатывает автоматизация.
Что могу посоветовать?
Для начала попробуйте с тем пультом, который уже есть. Может получится его дообучить до 100% совместимости с диалектом команд кондиционера. Это правда никак не поможет решить проблему с рассинхроном состояний, но по крайней мере сведет такие ситуации к минимуму.
Еспшка на мой взгляд перспективней с точки зрения возможностей и надежности, но потребуется самостоятельная работа руками:
1. купить
2. спаять
3. приладить в кондиционер
4. прошить/настроить
Готовы ли вы со всем этим возиться решать только вам )

**Comment by anpl5555** [comment]
А можете скинуть конфиг вашего template сенсора и автоматизацию, как пример? Буду очень благодарен..

**Comment by d1mdev** [comment]
**Сенсор:**
```
template:
    - binary_sensor:
      - name: room_climate_problem
        state: "{{ (is_state('binary_sensor.0x000000000000_contact', 'on') and is_state('climate.room_hvac', 'off')) or (is_state('binary_sensor.0x000000000000_contact', 'off') and not is_state('climate.room_hvac', 'off')) }}"
        delay_on: "0:00:20"
        delay_off: "0:00:20"
        device_class: problem
```
**где:**
binary_sensor.0x000000000000_contact - entity_id сенсора датчика открытия
climate.room_hvac - entity_id кондиционера

**Логика:**
Шторка кондиционера открыта - сенсор открытия в состоянии 'on', закрыта - 'off'. Если в течении 20 секунд состояния не совпадают сенсор room_climate_problem переходит в состояние 'on', что сигнализирует о наличии проблемы.
Время срабатывания подбирается эмпирически.
При выключении кондиционер еще какое-то время проветривает внутренний блок и только потом закрывает шторки, а HA, получив команду 'ВЫКЛ', уже считает, что кондиционер выключен. Вот, чтобы не было ложных срабатываний используется задержка.

**Ну и автоматизация:**

```
alias: room climate - sync failure
description: ""
mode: single
triggers:
  - entity_id:
      - binary_sensor.room_climate_problem
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 30
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ (is_state('binary_sensor.0x000000000000_contact', 'on') and
              is_state('climate.room_hvac', 'off')) }}
        sequence:
          - metadata: {}
            data: {}
            target:
              entity_id: switch.room_transmitter
            action: switch.turn_off
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - metadata: {}
            data:
              hvac_mode: cool
            target:
              entity_id: climate.room_hvac
            action: climate.set_hvac_mode
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - metadata: {}
            data: {}
            target:
              entity_id: switch.room_transmitter
            action: switch.turn_on
      - conditions:
          - condition: template
            value_template: >-
              {{ is_state('binary_sensor.0x000000000000_contact', 'off') and
              not is_state('climate.room_hvac', 'off') }}
        sequence:
          - metadata: {}
            data: {}
            target:
              entity_id: switch.room_transmitter
            action: switch.turn_off
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - metadata: {}
            data:
              hvac_mode: "off"
            target:
              entity_id: climate.room_hvac
            action: climate.set_hvac_mode
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - metadata: {}
            data: {}
            target:
              entity_id: switch.room_transmitter
            action: switch.turn_on
```

**где:**
binary_sensor.0x000000000000_contact - entity_id сенсора датчика открытия
climate.room_hvac - entity_id кондиционера
binary_sensor.room_climate_problem - сенсор наличия проблемы рассинхрона
switch.room_transmitter - entity_id переключателя, блокирующего непосредственно отправку команд на ИК приемник кондиционера (это важно, в компоненте этот перереключатель описан, у Я-пульта его естественно нет).

**Логика:**

При срабатывании вышеописанного сенсора _room_climate_problem_ автоматизация дополнительно ждет еще 30 сек и в зависимости от состояний кондиционера и сенсора открытия/закрытия приводит карточку HA в соответствие с фактическим статусом кондиционера. Разумеется знать, в каком конкретно режиме находится кондиционер (охлаждение/обогрев/проветривание) автоматизация не может, поэтому перевожу в охлаждение, как основной для моего применения.

Возможно у вас появится какое-то собственное решение.
